In [5]:
import os
os.chdir('Project/RL_shenlan/')
os.getcwd()

'/home/chj/Project/RL_shenlan'

# TicTacToe
TicTacToe 是一个简单的对抗游戏，棋盘大小为 3 × 3，谁先将 棋子连成线(横、竖、斜)，谁就获得胜利。(× 先手) 这里要求大家实 现以下功能:

## 用数值的方式表示状态、动作、奖励(+1/0/-1 区分胜/平/负)
环境类，环境能够根据智能体的动作给出反馈。即实现成员函数 step(a)→s, r
智能体类，并包含一个随机策略，即从剩下的空位中随机采样一 个位置下。函数形式 policy(s)→ a
通过仿真的方式，大量对弈，统计在都执行随机策略的情况下， 先手和后手胜利的概率。

我们首先要定义一个环境类，这个环境用一个numpy表示状态

分别用+1/-1/0表示X/O/空白

![](http://ww4.sinaimg.cn/large/006tNc79ly1g4xyan0d34j304v04v3yv.jpg)

In [6]:
from code1_intro import TicTacToeEnv, RandAgent

env = TicTacToeEnv()
agent1 = RandAgent()
agent2 = RandAgent()
state = env.reset()

# 这里给出了一次运行的代码参考
# 你可以按照自己的想法实现
# 多次实验，计算在双方随机策略下，先手胜/平/负的概率
while 1:
    current_player = env.getCurrentPlayer()
    if current_player == 1:
        action = agent1.policy(state)
    else:
        action = agent2.policy(state)
    next_state, reward, terminal = env.step(action)
    print(next_state)
    if terminal:
        winner = 'Player1' if env.getWinner() == 1 else 'Player2'
        print('Winner: {}'.format(winner))
        break
    state = next_state

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.]
 [-1.  1.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [-1.  1.  1.]
 [ 0.  0.  0.]]
[[ 0. -1.  0.]
 [-1.  1.  1.]
 [ 0.  0.  0.]]
[[ 0. -1.  0.]
 [-1.  1.  1.]
 [ 0.  1.  0.]]
[[ 0. -1.  0.]
 [-1.  1.  1.]
 [-1.  1.  0.]]
[[ 0. -1.  0.]
 [-1.  1.  1.]
 [-1.  1.  1.]]
[[-1. -1.  0.]
 [-1.  1.  1.]
 [-1.  1.  1.]]
Winner: Player2


'/home/chj'